name: Build Package and Push to AWS ECR 

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Checkout python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::401244505709:role/jjh_test
          role-session-name: OIDCSession # 추가 (oidc)
          role-duration-seconds: 3600 # 추가 (oidc)
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SERVICE_NAME: "onemodel_v3_test"
          STACK_TYPE: "test"
          VERSION: "2024.4.01"

        run: |
            echo $LATEST_TAG
            docker build -f ./onemodel_v3/Dockerfile --build-arg VERSION=$VERSION -t $ECR_REGISTRY/$SERVICE_NAME:latest .
            docker push -a $ECR_REGISTRY/$SERVICE_NAME
            aws ecs update-service --cluster aide --service $SERVICE_NAME --task-definition $SERVICE_NAME --force-new-deployment